Add profile for Ubiquiti Edgerouter X
wlanslovenija/nodewatcher pull request #35
Opened 2017-04-14 16:50 UTC by robimarko

Initial ERX support

2017-05-04 19:56 UTC, mitar commented
Please fix so that tests do not fail.

2017-05-04 23:16 UTC, robimarko commented
Finally got it to build without errors

2017-05-04 23:52 UTC, mitar commented
While this is passing tests, can you still make sure that code style matches other files? Pay close attention to newlines and code structure.

2017-05-05 07:38 UTC, robimarko commented
I compared this with one of your templates and I think that now it matches

2017-05-05 07:39 UTC, mitar approved these changes

2017-05-05 11:23 UTC, kostko requested changes
Some minor comments. It looks like the device descriptor is missing port mappings, see `port_map` in other descriptors. You have to configure this based on how the ports are called in LEDE.

Also, please squash all your commits into a single commit as this is a lot of changes to a single new file.

2017-05-05 11:23 UTC, kostko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +#Register Edgerouter X device
Space after `#`, dot at the end.

2017-05-05 11:23 UTC, kostko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +    identifier = 'ub-er-x'
Change identifier to `ub-edgerouter-x`.

2017-05-05 11:23 UTC, kostko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +                        ports=[0, 1, 2, 3, 4],
Did you check that this configuration is correct?

2017-05-05 12:58 UTC, robimarko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +                        ports=[0, 1, 2, 3, 4],
From what I know and from Lede source it should be correct.

2017-05-05 12:59 UTC, robimarko commented
I have tried to make changes to comply with your requests

2017-05-07 08:33 UTC, kostko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +            'sw0': cgm_devices.SwitchPortMap('switch0', vlans='eth0'),
Port mapping seems incorrect. You have set static `eth0` for all VLANs and also `wan0`. If the switch actually supports VLANs, the mapping should be something like `eth0.{vlan}`. But you need to set this based on how the switch is configured in LEDE, please check that (maybe link to the section in LEDE source where defaults for this device are configured).

But especially you can't have both the switch and `wan0` on the same interface (e.g. `eth0`). If the WAN port is actually part of the switch, it needs to be configured as a switch VLAN preset, similar to the LAN port (with the correct port definitions of course).

2017-05-07 10:02 UTC, robimarko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +            'sw0': cgm_devices.SwitchPortMap('switch0', vlans='eth0'),
Well that be beyond my understanding but I will try to figure it out.
Here is switch configuration in Lede source
https://github.com/lede-project/source/blob/master/target/linux/ramips/base-files/etc/board.d/02_network

ucidef_add_switch "switch0" \
			"1:lan" "2:lan" "3:lan" "4:lan" "0:wan" "6@eth0"

2017-05-07 10:14 UTC, kostko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +            'sw0': cgm_devices.SwitchPortMap('switch0', vlans='eth0'),
To me, this reads as follows:
* All ports (LAN and WAN) are connected via the switch (so your configuration above is wrong, you should not define the WAN port separately).
* VLANs are attached to `eth0`, so they will be `eth0.{vlan}`.
* Ports `1, 2, 3, 4` are assigned to the LAN VLAN.
* Port `0` is assigned to the WAN VLAN.
* Port `6` is connected to the CPU (so it must be in all VLANs).

I am not sure, so you should really check this on an actual device (e.g. with a default LEDE install).

2017-05-07 10:23 UTC, robimarko commented on nodewatcher/modules/devices/ubnt/edgerouter.py
> +            'sw0': cgm_devices.SwitchPortMap('switch0', vlans='eth0'),
Ok,@valentt has one flashed with LEDE so I will check it out.

2017-05-08 20:49 UTC, robimarko commented
Here is output from swconfig on Lede
root@LEDE:/# swconfig dev switch0 show
Global attributes:
	enable_vlan: 1
	mib: Switch MIB counters
PPE_AC_BCNT0: 0
PPE_AC_PCNT0: 0
PPE_AC_BCNT63: 0
PPE_AC_PCNT63: 0
PPE_MTR_CNT0: 0
PPE_MTR_CNT63: 0
GDM1_TX_GBCNT: 0
GDM1_TX_GPCNT: 0
GDM1_TX_SKIPCNT: 0
GDM1_TX_COLCNT: 0
GDM1_RX_GBCNT1: 0
GDM1_RX_GPCNT1: 0
GDM1_RX_OERCNT: 0
GDM1_RX_FERCNT: 0
GDM1_RX_SERCNT: 0
GDM1_RX_LERCNT: 0
GDM1_RX_CERCNT: 0
GDM1_RX_FCCNT: 0
GDM2_TX_GBCNT: 0
GDM2_TX_GPCNT: 0
GDM2_TX_SKIPCNT: 0
GDM2_TX_COLCNT: 0
GDM2_RX_GBCNT: 0
GDM2_RX_GPCNT: 0
GDM2_RX_OERCNT: 0
GDM2_RX_FERCNT: 0
GDM2_RX_SERCNT: 0
GDM2_RX_LERCNT: 0
GDM2_RX_CERCNT: 0
GDM2_RX_FCCNT: 0

Port 0:
	mib: Port 0 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 2
	link: port:0 link:down
Port 1:
	mib: Port 1 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 1
	link: port:1 link:down
Port 2:
	mib: Port 2 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 1
	link: port:2 link:down
Port 3:
	mib: Port 3 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 1
	link: port:3 link:down
Port 4:
	mib: Port 4 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 1
	link: port:4 link:down
Port 5:
	mib: Port 5 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 0
	link: port:5 link:down
Port 6:
	mib: Port 6 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 57
RxUni      : 0
RxMulti    : 37
RxBroad    : 20
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 22
Rx128Byte  : 15
Rx256Byte  : 19
Rx512Byte  : 0
Rx1024Byte : 1
RxByte     : 12150
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 0
	link: port:6 link:up speed:1000baseT full-duplex 
Port 7:
	mib: Port 7 MIB counters
TxDrop     : 0
TxCRC      : 0
TxUni      : 0
TxMulti    : 0
TxBroad    : 0
TxCollision: 0
TxSingleCol: 0
TxMultiCol : 0
TxDefer    : 0
TxLateCol  : 0
TxExcCol   : 0
TxPause    : 0
Tx64Byte   : 0
Tx65Byte   : 0
Tx128Byte  : 0
Tx256Byte  : 0
Tx512Byte  : 0
Tx1024Byte : 0
TxByte     : 0
RxDrop     : 0
RxFiltered : 0
RxUni      : 0
RxMulti    : 0
RxBroad    : 0
RxAlignErr : 0
RxCRC      : 0
RxUnderSize: 0
RxFragment : 0
RxOverSize : 0
RxJabber   : 0
RxPause    : 0
Rx64Byte   : 0
Rx65Byte   : 0
Rx128Byte  : 0
Rx256Byte  : 0
Rx512Byte  : 0
Rx1024Byte : 0
RxByte     : 0
RxCtrlDrop : 0
RxIngDrop  : 0
RxARLDrop  : 0

	pvid: 0
	link: port:7 link:down
VLAN 1:
	vid: 0
	ports: 1 2 3 4 6t 
VLAN 2:
	vid: 0
	ports: 0 6t

2017-05-09 07:20 UTC, kostko commented
Can you also paste the output of `uci show network`?

2017-05-09 08:40 UTC, robimarko commented
Sure,here it is
https://pastebin.com/2u5gg01a

2017-05-12 11:25 UTC, robimarko commented
I have finally got around to fixing switch configuration.
Now it should be correct as per LEDE

2017-05-13 13:53 UTC, kostko commented
Looks good (note that we haven't yet built LEDE for `ramips_mt7621`), it would just be nice if you could squash all your commits into a single one and change the commit message to `devices: Add profile for Ubiquiti Edgerouter X.` Do you know how to squash commits?

2017-05-13 13:54 UTC, robimarko commented
Unfortunatelly not.

2017-05-13 14:21 UTC, kostko commented
Please first rebase on `development` as there have been some updates to that branch (802.11ac support).

2017-05-13 14:34 UTC, robimarko commented
Should be done.

2017-05-13 14:44 UTC, kostko commented
Ok, so you merged instead of rebasing, which introduced yet more commits :-)

Are you using the command-line Git client? If so, do the following to correctly rebase your commits and squash them.

First get the latest changes and rebase (instead of merge):
```
git fetch origin
git rebase origin/development
```

Then squash your last 10 commits by running:
```
git rebase -i HEAD~10
```

This will open an editor that will enable you to interactively update the commits, sorted from oldest to newest.  For the first one, keep the `pick` command. For all the next ones change `pick` to `squash`. Save and exit the editor.

Then, the editor will stop for squashing commits. Edit the commit message to say `devices: Add profile for Ubiquiti Edgerouter X.` (e.g., remove all the other lines). Save and exit the editor.

This should now give you a single commit in your history containing all your changes (check this with `git log`). Once you are sure that everything is correct, run `git push -f` to overwrite your PR branch.

I can do all of this for you, but I would like you to learn how to do this yourself, so it will be easier next time.

2017-05-13 14:52 UTC, robimarko commented
I am trying but I can find commits for Edgerouter X,only UAP

2017-05-13 14:56 UTC, kostko commented
Be sure that you are on the correct branch before doing anything. To switch to this branch do `git checkout patch-1` before all other commands.

2017-05-13 15:01 UTC, robimarko commented
Now it should be done

2017-05-13 15:12 UTC, kostko commented
Nope, something does not seem right? You seem to have combined the two different branches into one?

2017-05-13 15:23 UTC, kostko commented
Also it seems that you don't have the correct e-mail address configured in `git`?

2017-05-13 16:09 UTC, robimarko commented
I dont get how could I combine two branches?
I used patch-1 branch and then squashed commits into one.
I used same email as in my github account

2017-05-13 17:14 UTC, mitar commented
I think the problem is that @robimarko is working on `development` branch for #36.

@robimarko, please **do not** now just close this or the other pull request and open new ones, but fix them instead. Learn to do that.

2017-05-14 23:00 UTC, robimarko commented
Proper PR done.
Check PR #39

2017-05-14 23:00 UTC, closed without merging